/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlaceholderImage {
        "height": number;
        "text"?: string;
        "width": number;
    }
    interface PlaceholderText {
        "itemHeight"?: number;
    }
}
declare global {
    interface HTMLPlaceholderImageElement extends Components.PlaceholderImage, HTMLStencilElement {
    }
    var HTMLPlaceholderImageElement: {
        prototype: HTMLPlaceholderImageElement;
        new (): HTMLPlaceholderImageElement;
    };
    interface HTMLPlaceholderTextElement extends Components.PlaceholderText, HTMLStencilElement {
    }
    var HTMLPlaceholderTextElement: {
        prototype: HTMLPlaceholderTextElement;
        new (): HTMLPlaceholderTextElement;
    };
    interface HTMLElementTagNameMap {
        "placeholder-image": HTMLPlaceholderImageElement;
        "placeholder-text": HTMLPlaceholderTextElement;
    }
}
declare namespace LocalJSX {
    interface PlaceholderImage {
        "height"?: number;
        "text"?: string;
        "width"?: number;
    }
    interface PlaceholderText {
        "itemHeight"?: number;
    }
    interface IntrinsicElements {
        "placeholder-image": PlaceholderImage;
        "placeholder-text": PlaceholderText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "placeholder-image": LocalJSX.PlaceholderImage & JSXBase.HTMLAttributes<HTMLPlaceholderImageElement>;
            "placeholder-text": LocalJSX.PlaceholderText & JSXBase.HTMLAttributes<HTMLPlaceholderTextElement>;
        }
    }
}
