/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlaceholderText {
        "fillColor"?: string;
    }
}
declare global {
    interface HTMLPlaceholderTextElement extends Components.PlaceholderText, HTMLStencilElement {
    }
    var HTMLPlaceholderTextElement: {
        prototype: HTMLPlaceholderTextElement;
        new (): HTMLPlaceholderTextElement;
    };
    interface HTMLElementTagNameMap {
        "placeholder-text": HTMLPlaceholderTextElement;
    }
}
declare namespace LocalJSX {
    interface PlaceholderText {
        "fillColor"?: string;
    }
    interface IntrinsicElements {
        "placeholder-text": PlaceholderText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "placeholder-text": LocalJSX.PlaceholderText & JSXBase.HTMLAttributes<HTMLPlaceholderTextElement>;
        }
    }
}
